# Generated by Django 5.0.7 on 2024-08-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='log',
            new_name='log_text',
        ),
    ]
